/* license: https://mit-license.org
 *
 *  DIMP : Decentralized Instant Messaging Protocol
 *
 *                                Written in 2020 by Moky <albert.moky@gmail.com>
 *
 * ==============================================================================
 * The MIT License (MIT)
 *
 * Copyright (c) 2020 Albert Moky
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 * ==============================================================================
 */
package mkm

import (
	. "github.com/dimchat/mkm-go/crypto"
	. "github.com/dimchat/mkm-go/protocol"
)

/**
 *  Entity Delegate
 *  ~~~~~~~~~~~~~~~
 */
type EntityDelegate interface {

	/**
	 *  Create user with ID
	 *
	 * @param uid - user ID
	 * @return user
	 */
	GetUser(uid ID) User

	/**
	 *  Create group with ID
	 *
	 * @param gid - group ID
	 * @return group
	 */
	GetGroup(gid ID) Group
}

/**
 *  Entity Data Source
 *
 *  <pre>
 *  1. meta for user, which is generated by the user's private key
 *  2. meta for group, which is generated by the founder's private key
 *  3. meta key, which can verify message sent by this user(or founder)
 *  4. visa key, which can encrypt message for the receiver(user)
 *  </pre>
 */
type EntityDataSource interface {
	GroupDataSource
	UserDataSource

	/**
	 *  Get meta for entity ID
	 *
	 * @param did - entity ID
	 * @return Meta object
	 */
	GetMeta(did ID) Meta

	/**
	 *  Get documents for entity ID
	 *
	 * @param did - entity ID
	 * @return Document list
	 */
	GetDocuments(did ID) []Document
}

/**
 *  Group Data Source
 *
 *  <pre>
 *  1. founder has the same public key with the group's meta.key
 *  2. owner and members should be set complying with consensus algorithm
 *  </pre>
 */
type GroupDataSource interface {

	/**
	 *  Get founder of the group
	 *
	 * @param group - group ID
	 * @return fonder ID
	 */
	GetFounder(group ID) ID

	/**
	 *  Get current owner of the group
	 *
	 * @param group - group ID
	 * @return owner ID
	 */
	GetOwner(group ID) ID

	/**
	 *  Get all members in the group
	 *
	 * @param group - group ID
	 * @return members list (ID)
	 */
	GetMembers(group ID) []ID
}

/**
 *  User Data Source
 *
 *  <pre>
 *  (Encryption/decryption)
 *  1. public key for encryption
 *     if visa.key not exists, means it is the same key with meta.key
 *  2. private keys for decryption
 *     the private keys paired with [visa.key, meta.key]
 *
 *  (Signature/Verification)
 *  3. private key for signature
 *     the private key paired with visa.key or meta.key
 *  4. public keys for verification
 *     [visa.key, meta.key]
 *
 *  (Visa Document)
 *  5. private key for visa signature
 *     the private key pared with meta.key
 *  6. public key for visa verification
 *     meta.key only
 *  </pre>
 */
type UserDataSource interface {

	/**
	 *  Get contacts list
	 *
	 * @param user - user ID
	 * @return contacts list (ID)
	 */
	GetContacts(user ID) []ID

	/**
	 *  Get user's private keys for decryption
	 *  <blockquote>
	 *      (which paired with [visa.key, meta.key])
	 *  </blockquote>
	 *
	 * @param user - user ID
	 * @return private keys
	 */
	GetPrivateKeysForDecryption(user ID) []DecryptKey

	/**
	 *  Get user's private key for signature
	 *  <blockquote>
	 *      (which paired with visa.key or meta.key)
	 *  </blockquote>
	 *
	 * @param user - user ID
	 * @return private key
	 */
	GetPrivateKeyForSignature(user ID) SignKey

	/**
	 *  Get user's private key for signing visa
	 *
	 * @param user - user ID
	 * @return private key
	 */
	GetPrivateKeyForVisaSignature(user ID) SignKey
}
